CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    modified TIMESTAMP NOT NULL DEFAULT now(),
    folder_id INTEGER REFERENCES noteful_folders(id),
    content TEXT
);